services:
  manejo_clientes:
    build: manejo_clientes
    ports:
      - "9000:8080"
    environment:
      # Remove DB_URL, DB_USER_NAME, and DB_PASSWORD environment variables
    spring:
      datasource:
        url: jdbc:mysql://gestion_client:3306/gestion_clientes
        username: anamyAdmin
        password: 1234
    restart: always
    depends_on:
      - gestion_client:
          condition: service_healthy

  gestion_client:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: gestion_clientes
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
